### PR TITLE
The rest of seimspeed events

### PR DESCRIPTION
**Pull request by calebwatinga**
These are that ahave been recently updated.

### CODE REVIEW

**Comment by jeremykes** [comment]
Bro you legend. That was quick. Ok I am working on notifications now so will complete and advice. Skimmed through all your code and it looks good!

**Comment by calebwatinga** [comment]
Thanks. You might have to do some alterations because i just added the ones
that i associated them with the events.

**Comment by jeremykes** [comment]
Yes we will do that on the fly when we are doing the listeners. It might be overkill at this point so lets add them when we need them.

Thanks bro. I will send over some more stuff soonish...

**Comment by calebwatinga** [comment]
Ok. Let me know whenever.

**Pull request merged**
